### ISSUE TITLE
Cant seem to get Breezy to work on ubuntu

### ISSUE THREAD

**Issue by Superpat** [wheaney/breezy-desktop#34] opened 2024-07-22 14:30 UTC
Hello, just received a pair of viture one xr glasses and I was testing them out. I tried installing breezy, but even though the install seems to have worked, playing with the options does not change anything.

I'm running ubuntu 23.10 and gnome 45.2 and my displays are joined.

`breezy_gnome_verify` reports that the installation is fine, `xreal_driver_config -s` says it's enabled and the breezy app says that viture one is connected but when I toggle options on and off, they dont seem to do anything.

What's the next step for figuring out what's happening ?

**Comment by erkkimon** [comment] 2024-07-24 10:35
I have exactly the same problem but on Arch Linux. I got the glasses today so I might do something wrong with the device itself.

I can see the joined display mirrored on my Viture One glasses, and the options don't affect what I see through glasses. I have rebooted my laptop multiple times and also force reset the Breezy app.

Here is some version information and such.

```
pacman -Qs 'xr-' && pacman -Qs 'breezy'
local/xr-driver-breezy-gnome-git 0.10.2-4
    XR Linux Driver for Breezy GNOME
local/breezy-desktop-gnome-git 0.10.2-2
    Breezy GNOME - XR desktop
local/xr-driver-breezy-gnome-git 0.10.2-4
    XR Linux Driver for Breezy GNOME

gnome-shell --version
GNOME Shell 46.3.1

xreal_driver_config -s
enabled
```

I will gladly provide more info whatever seems to be useful.

**Comment by wheaney** [comment] 2024-07-24 21:14
Hi, can you both update your respective setups (@Superpat rerun the setup script, @erkkimon via `yay`) and try again? I've pushed out some pretty big updates over the last couple days, including some stability things. @erkkimon make sure you're using "join" mode with the glasses in display settings, not `mirror`.

If you're still having issues, please attach the following:
* Driver logs: `~/.local/state/xr_driver/driver.log`
* Extension logs: `~/.local/state/breezy_gnome/logs/gjs/[date].log`

**Comment by erkkimon** [comment] 2024-07-25 13:45
Okay, something seemed to change after removing Breezy (pikaur -R breezy-desktop-gnome-git) and reinstalling it (pikaur -S breezy-desktop-gnome-git).

Now I get "No licence file was found". 

![Screenshot from 2024-07-25 16-43-47](https://github.com/user-attachments/assets/8c5e3be2-055b-4ec8-869d-cec3df159404)
![Screenshot from 2024-07-25 16-43-39](https://github.com/user-attachments/assets/1f69678c-4796-4f13-bed6-99d161322791)

According to device_licence the trial should be active, if I interpret the JSON-like data right.

Here are my logs and the device_licence file:

```
[erkkimon@liquiditee ~]$ cat ~/.local/state/xr_driver/driver.log
cat: /home/erkkimon/.local/state/xr_driver/driver.log: No such file or directory
[erkkimon@liquiditee ~]$ cat ~/.local/state/breezy_gnome/logs/gjs/2024-07-2
2024-07-24.log  2024-07-25.log  
[erkkimon@liquiditee ~]$ cat ~/.local/state/breezy_gnome/logs/gjs/2024-07-25.log 
breezydesktop: Monitor change detected
breezydesktop: Monitor change detected
breezydesktop: Gnome-Shell 46.3.1 / gjs 1.80.2 (18002) / x11
breezydesktop: Monitor change detected
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
breezydesktop: Gnome-Shell 46.3.1 / gjs 1.80.2 (18002) / x11
breezydesktop: Monitor change detected
breezydesktop: Identified supported monitor: VITURE on DP-1
[erkkimon@liquiditee ~]$ cat ~/.local/state/xr_driver/device_license 
{"license":"{\"hardwareId\":\"XXXXX\",\"tiers\":{\"subscriber\":{\"active\":false,\"fundsToRenew\":false,\"fundsNeededUSD\":5,\"lifetimeFundsNeededUSD\":125,\"fundsNeededByPeriod\":{\"monthly\":5,\"yearly\":50,\"lifetime\":125}}},\"features\":{\"productivity_basic\":{\"status\":\"trial\",\"endDate\":1726997320}}}","signature":"XXXXX"}
[erkkimon@liquiditee ~]$ pacman -Qs 'xr-' && pacman -Qs 'breezy'
local/xr-driver-breezy-gnome-git 0.10.5-1
    XR Linux Driver for Breezy GNOME
local/breezy-desktop-gnome-git 0.10.5-1
    Breezy GNOME - XR desktop
local/xr-driver-breezy-gnome-git 0.10.5-1
    XR Linux Driver for Breezy GNOME
[erkkimon@liquiditee ~]$
```

**Comment by erkkimon** [comment] 2024-07-25 15:23
Thanks for looking into this @wheaney!

I can't seem to get the driver running anymore. Here is the whole process that I tried.

```
[erkkimon@liquiditee ~]$ systemctl --user enable --now xreal-air-driver.service
Failed to enable unit: Unit xreal-air-driver.service does not exist
[erkkimon@liquiditee ~]$ xreal_driver_config -s
bash: xreal_driver_config: command not found
[erkkimon@liquiditee ~]$ pikaur -R xr-driver-breezy-gnome-git
[sudo] password for erkkimon: 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing xr-driver-breezy-gnome-git breaks dependency 'xr-driver-breezy-gnome-git' required by breezy-desktop-gnome-git
[erkkimon@liquiditee ~]$ pikaur -S xr-driver-breezy-gnome-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 xr-driver-breezy-gnome-git            0.10.5-1             -> 0.10.5-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: warning: Not showing diff for xr-driver-breezy-gnome-git package (already reviewed)
Do you want to edit PKGBUILD for xr-driver-breezy-gnome-git package? [y/N] n
Do you want to edit hooks.install for xr-driver-breezy-gnome-git package? [y/N] n

:: Downloading the latest sources for a devel package xr-driver-breezy-gnome-git...
:: Package xr-driver-breezy-gnome-git is already built. Pass '--rebuild' flag to force the build.

loading packages...
warning: xr-driver-breezy-gnome-git-0.10.5-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) xr-driver-breezy-gnome-git-0.10.5-1

Total Installed Size:  0.69 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                                 [############################################################################] 100%
(1/1) checking package integrity                                                                                               [############################################################################] 100%
(1/1) loading package files                                                                                                    [############################################################################] 100%
(1/1) checking for file conflicts                                                                                              [############################################################################] 100%
(1/1) checking available disk space                                                                                            [############################################################################] 100%
:: Processing package changes...
(1/1) reinstalling xr-driver-breezy-gnome-git                                                                                  [############################################################################] 100%
:: Running post-transaction hooks...
(1/3) Reloading user manager configuration...
(2/3) Reloading device manager configuration...
(3/3) Arming ConditionNeedsUpdate...
[erkkimon@liquiditee ~]$ xreal_driver_config -s
bash: xreal_driver_config: command not found
[erkkimon@liquiditee ~]$ systemctl --user enable --now xreal-air-driver.service
Failed to enable unit: Unit xreal-air-driver.service does not exist
[erkkimon@liquiditee ~]$ # Did not work, let's uninstall everything and then reinstall
[erkkimon@liquiditee ~]$ pikaur -Rns breezy-desktop-gnome-git
checking dependencies...

Packages (3) python-pydbus-0.6.0-11  xr-driver-breezy-gnome-git-0.10.5-1  breezy-desktop-gnome-git-0.10.5-1

Total Removed Size:  1.67 MiB

:: Do you want to remove these packages? [Y/n] y
:: Processing package changes...
(1/3) removing breezy-desktop-gnome-git                                                                                        [############################################################################] 100%
(2/3) removing xr-driver-breezy-gnome-git                                                                                      [############################################################################] 100%
(3/3) removing python-pydbus                                                                                                   [############################################################################] 100%
:: Running post-transaction hooks...
(1/6) Reloading user manager configuration...
(2/6) Reloading device manager configuration...
(3/6) Arming ConditionNeedsUpdate...
(4/6) Compiling GSettings XML schema files...
(5/6) Updating icon theme caches...
(6/6) Updating the desktop file MIME type cache...
[erkkimon@liquiditee ~]$ pikaur -Rns xr-driver-breezy-gnome-git
error: target not found: xr-driver-breezy-gnome-git
[erkkimon@liquiditee ~]$ pikaur -S xr-driver-breezy-gnome-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 xr-driver-breezy-gnome-git                                 -> 0.10.5-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: warning: Not showing diff for xr-driver-breezy-gnome-git package (already reviewed)
Do you want to edit PKGBUILD for xr-driver-breezy-gnome-git package? [y/N] n
Do you want to edit hooks.install for xr-driver-breezy-gnome-git package? [y/N] n

:: Downloading the latest sources for a devel package xr-driver-breezy-gnome-git...
:: Package xr-driver-breezy-gnome-git is already built. Pass '--rebuild' flag to force the build.

loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) xr-driver-breezy-gnome-git-0.10.5-1

Total Installed Size:  0.69 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                                 [############################################################################] 100%
(1/1) checking package integrity                                                                                               [############################################################################] 100%
(1/1) loading package files                                                                                                    [############################################################################] 100%
(1/1) checking for file conflicts                                                                                              [############################################################################] 100%
(1/1) checking available disk space                                                                                            [############################################################################] 100%
:: Processing package changes...
(1/1) installing xr-driver-breezy-gnome-git                                                                                    [############################################################################] 100%
start service after install: systemctl --user enable --now xr-driver.service
:: Running post-transaction hooks...
(1/3) Reloading user manager configuration...
(2/3) Reloading device manager configuration...
(3/3) Arming ConditionNeedsUpdate...
[erkkimon@liquiditee ~]$ pikaur -S breezy-desktop-gnome-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: New dependencies will be installed from repository:
 meson (for breezy-desktop-gnome-git)                       -> 1.5.0-1
 ninja (for meson, breezy-desktop-gnome-git)                -> 1.12.1-1
 python-pydbus (for breezy-desktop-gnome-git)               -> 0.6.0-11
 python-tqdm (for meson)                                    -> 4.66.4-1

:: AUR package will be installed:
 breezy-desktop-gnome-git                                   -> 0.10.5-1

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: warning: Not showing diff for breezy-desktop-gnome-git package (already reviewed)
Do you want to edit PKGBUILD for breezy-desktop-gnome-git package? [y/N] n

Reading local package database...
:: Installing repository dependencies for breezy-desktop-gnome-git:
resolving dependencies...
looking for conflicting packages...

Packages (4) python-tqdm-4.66.4-1  meson-1.5.0-1  ninja-1.12.1-1  python-pydbus-0.6.0-11

Total Installed Size:  13.86 MiB

:: Proceed with installation? [Y/n] Y
(4/4) checking keys in keyring                                                                                                 [############################################################################] 100%
(4/4) checking package integrity                                                                                               [############################################################################] 100%
(4/4) loading package files                                                                                                    [############################################################################] 100%
(4/4) checking for file conflicts                                                                                              [############################################################################] 100%
(4/4) checking available disk space                                                                                            [############################################################################] 100%
:: Processing package changes...
(1/4) installing ninja                                                                                                         [############################################################################] 100%
(2/4) installing python-tqdm                                                                                                   [############################################################################] 100%
Optional dependencies for python-tqdm
    python-requests: telegram [installed]
(3/4) installing meson                                                                                                         [############################################################################] 100%
(4/4) installing python-pydbus                                                                                                 [############################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Reading local package database...
:: Downloading the latest sources for a devel package breezy-desktop-gnome-git...
:: Package breezy-desktop-gnome-git is already built. Pass '--rebuild' flag to force the build.

:: Removing already installed dependencies for breezy-desktop-gnome-git:
checking dependencies...
:: cmake optionally requires ninja: for ninja generator

Packages (4) meson-1.5.0-1  ninja-1.12.1-1  python-pydbus-0.6.0-11  python-tqdm-4.66.4-1

Total Removed Size:  13.86 MiB

:: Do you want to remove these packages? [Y/n] Y
:: Processing package changes...
(1/4) removing meson                                                                                                           [############################################################################] 100%
(2/4) removing ninja                                                                                                           [############################################################################] 100%
(3/4) removing python-tqdm                                                                                                     [############################################################################] 100%
(4/4) removing python-pydbus                                                                                                   [############################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (2) python-pydbus-0.6.0-11  breezy-desktop-gnome-git-0.10.5-1

Total Installed Size:  0.98 MiB

:: Proceed with installation? [Y/n] Y
(2/2) checking keys in keyring                                                                                                 [############################################################################] 100%
(1/2) checking package integrity                                                                                               [############################################################################] 100%
(1/2) loading package files                                                                                                    [############################################################################] 100%
(2/2) checking for file conflicts                                                                                              [############################################################################] 100%
(2/2) checking available disk space                                                                                            [############################################################################] 100%
:: Processing package changes...
(1/2) installing python-pydbus                                                                                                 [############################################################################] 100%
(2/2) installing breezy-desktop-gnome-git                                                                                      [############################################################################] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Compiling GSettings XML schema files...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
(reverse-i-search)`xr_': vim ~/.local/state/^C_driver/device_license 
[erkkimon@liquiditee ~]$ xreal_driver_config -s
bash: xreal_driver_config: command not found
[erkkimon@liquiditee ~]$ systemctl --user enable --now xreal-air-driver.service
Failed to enable unit: Unit xreal-air-driver.service does not exist
[erkkimon@liquiditee ~]$ xreal_driver_config -s
bash: xreal_driver_config: command not found
```

**Comment by wheaney** [comment] 2024-07-25 15:29
Oops! I recently renamed and reorganized all the files in the driver and breezy and forgot to update that setup step. The service is called `xr-driver` now, instead of `xreal-air-driver`. So replace that in your systemctl command. Siimilarly, the config script has been replaced with `xr_driver_cli` and it's in your path, so you don't need to put a full path to the script to run it.

**Comment by erkkimon** [comment] 2024-07-25 15:38
I can confirm that the problem was in naming. Now the driver seems to run fine. I will log out and log back in to see if everything works now, but I drop the BASH history here before that for the record.

```
[erkkimon@liquiditee ~]$ systemctl --user enable --now xr-driver.service
Created symlink '/home/erkkimon/.config/systemd/user/default.target.wants/xr-driver.service' → '/usr/lib/systemd/user/xr-driver.service'.
[erkkimon@liquiditee ~]$ xr_driver_cli -s
enabled
```

**Comment by Superpat** [comment] 2024-07-25 16:03
Hello @wheaney I just did a reinstall, but it didnt change anything. 

[driver.log](https://github.com/user-attachments/files/16380653/driver.log)
[2024-07-25.log](https://github.com/user-attachments/files/16380659/2024-07-25.log)

And here's the breazy log from before the update:
[2024-07-22.log](https://github.com/user-attachments/files/16380662/2024-07-22.log)

**Comment by erkkimon** [comment] 2024-07-25 16:06
The end result still seems to the same as in the beginning; no toggle or range input takes effect. But the logs look now more promising since there are errors. I tried changing the value of every toggle and range input for the sake of debugging. 

Please see the logs enclosed. They were quite massive to be pasted so I added them as files.

[2024-07-25.log](https://github.com/user-attachments/files/16380698/2024-07-25.log)

[driver.log](https://github.com/user-attachments/files/16380691/driver.log)

**Comment by wheaney** [comment] 2024-07-25 16:25
Whoa! You're both seeing the same issue from the extension: `Logical monitor scales must be identical`. You're both on X11 so maybe this is an issue I'm not seeing because I'm on Wayland.

One thing I forgot to have you do (sorry to keep sending you in circles) that will put extra details in your GJS logs: `dconf write /com/xronlinux/BreezyDesktop/debug true` then truncate your GJS log (e.g. `truncate -s 0 ~/.local/state/breezy_gnome/logs/gjs/[date].log`), log out and back in, reproduce the issue, and re-send me the log.

**Comment by wheaney** [comment] 2024-07-25 16:27
Btw, I think this would be resolved if you disabled `Find optimal display config` in the advanced settings, but I'd like to get the debug logs first, before you do that. :)

**Comment by erkkimon** [comment] 2024-07-25 16:41
You are correct, I run X11. 

I will send the logs as soon as I get back home. Let's see whether I or @Superpat has the chance to do it first. 😁

I tried toggling "Find optimal display config" but it didn't solve the problem. Of course logging out after toggling that could have changed the scenario.

**Comment by Superpat** [comment] 2024-07-25 17:02
Log after change:

[2024-07-25.log](https://github.com/user-attachments/files/16381413/2024-07-25.log)

**Comment by wheaney** [comment] 2024-07-25 17:09
@Superpat that last log didn't reproduce the same issue, it never got to the point where it tried to start up the effect. Either the driver wasn't running or ran into some error or you unplugged too soon (I don't have timestamps in the logs so it's hard to tell, but I'll assume you probably waited long enough). Can you try it a few more times, maybe do a restart or just a re-log?

**Comment by wheaney** [comment] 2024-07-25 17:20
I've pushed another revision of breezy that abides by the global scaling rule. Rerunning the setup script or getting the latest AUR release should prevent the `Logical monitor scales must be identical` error and allow you to re-enable ` Find optimal display config`.

**Comment by Superpat** [comment] 2024-07-25 17:23
Heres the log after messing with it a bit more and doing a reboot: [2024-07-25.log](https://github.com/user-attachments/files/16381633/2024-07-25.log)

havent tried your new revision yet

**Comment by Superpat** [comment] 2024-07-25 17:30
With the new revision and a reboot (note that I forgot to truncate this time): [2024-07-25.log](https://github.com/user-attachments/files/16381695/2024-07-25.log)

**Comment by wheaney** [comment] 2024-07-25 18:08
@Superpat in your most recent log it finally got to a point where it enabled the effect:
```
breezydesktop: Ready, enabling XR effect
breezydesktop: 	DEBUG - BreezyDesktopExtension _effect_enable
```

But then the device was unplugged or otherwise disconnected (Breezy can't trigger this, so something else caused it if you didn't unplug). Did you see the effect?

**Comment by erkkimon** [comment] 2024-07-25 18:49
My logs after setting debug true, before updating to the latest revision. Next I will take the new revision.

[2024-07-25.log](https://github.com/user-attachments/files/16382476/2024-07-25.log)
[driver.log](https://github.com/user-attachments/files/16382477/driver.log)

**Comment by erkkimon** [comment] 2024-07-25 20:22
Okay now after upgrading the breezy-desktop package via AUR it somewhat works! Thanks @wheaney!

In the beginning for once, until the first boot, also widescreen mode worked. After that widescreen mode makes my view blank, but a few times I got widescreen working. At the moment I'm writing this using XR mode + widescreen but I'm not sure when I get this combo working again so I decided to utilize the chance. :D

However, looks like XR mode works quite consistently when I (1) turn off widescreen mode, (2) unplug the glasses, (3) plug the glasses in. After that, XR mode can be quite consistently broken whenever I try to turn widescreen mode on, the glasses turn blank until I unplug again.

Here are my logs after upgrading (includes the getting XR + widescreen working because of unknown magic):
[driver.log](https://github.com/user-attachments/files/16383350/driver.log)
[2024-07-25.log](https://github.com/user-attachments/files/16383351/2024-07-25.log)

By the way, would it be better to open a new issue about the widescreen problem? This issue is about making options work, and at least in my setup options take effect.

PS. Thank you for starting up this project! This is already more usable than SpaceWalker which is unusable (for me at least) because Mission Control doesn't work and I think it can't work because of OSX-related restrictions which don't exist in open source world. There are definitely some rough edges still which is expected at this point, but I believe this can be something extraordinary because of choosing open source environment! I hope I can do my part in debugging, and hopefully I find a way to contribute in the code also. :)

**Comment by wheaney** [comment] 2024-07-25 20:31
The issue you're running into may be a known one, try turning off the "fast sbs switching" option in the advanced setting to see if it resolves it. In general widescreen has introduced a bit more instability because it relies on a mode switch in the glasses and that's kind of an unusual case that GNOME (or maybe the hardware) isn't really built to handle (a "monitor" quickly disconnecting and reconnecting with a difference resolution). So I put that switching mode in with the hope that people can get it working well in one or the other state.

I appreciate all the kind words. And your patience in dealing with this issue. :smile:

**Comment by wheaney** [comment] 2024-07-25 20:32
@Superpat I've put in a couple more fixes and some additional logging if you don't mind re-running the setup script.

**Comment by wheaney** [comment] 2024-08-13 18:13
Closing this since I think we resolved everything.

**Closed by wheaney** 2024-08-13 18:13 UTC
